### ISSUE TITLE
Django 1.8 Version

### ISSUE THREAD

**Issue by halfnibble** [halfnibble/django-light#2]
Anyone have comments on how I should handle new Django releases?

Since this is really just for demonstration purposes, should I only support the latest Django version?

Thanks.

**Comment by rnevius** [comment]
Is 1.8 going to change this at all? I think it makes sense to support the latest version +/- 1 in either direction. This keeps the project on the "cutting edge" while still ensuring people on slightly old versions can still benefit as they upgrade to the latest version.

**Comment by halfnibble** [comment]
Thanks for input.
